version: "3.5"

services:

  # Transaction Builder Web Service
  adosia-market-tx-builder-web:
    build:
      context: ..
      dockerfile: docker/Web.Dockerfile
      args:
        LINUX_USERNAME: ${LINUX_USERNAME}
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}
        CARDANO_NODE_VERSION: ${CARDANO_NODE_VERSION}
        CARDANO_NODE_BUILD: ${CARDANO_NODE_BUILD}
        CARDANO_NETWORK: ${CARDANO_NETWORK}
    container_name: adosia-market-tx-builder-web
    restart: unless-stopped
    user: "${CURRENT_UID}:${CURRENT_GID}"
    tty: true
    networks: [ adosia-market-tx-builder ]
    volumes:
      - ../application:/home/${LINUX_USERNAME}/application
      - ../cardano-node-data:/home/${LINUX_USERNAME}/cardano-node-data
    environment:
      - CARDANO_NODE_SOCKET_PATH=/home/${LINUX_USERNAME}/cardano-node-data/db/node.socket
      - LINUX_USERNAME=${LINUX_USERNAME}
      - CARDANO_NETWORK=${CARDANO_NETWORK}
    ports:
      - "8030:80"
      - "6000:6000"

  # Transaction Builder NodeJS Service
  adosia-market-tx-builder-nodejs:
    build:
      context: ..
      dockerfile: docker/NodeJS.Dockerfile
    container_name: adosia-market-tx-builder-nodejs
    restart: unless-stopped
    user: "${CURRENT_UID}:${CURRENT_GID}"
    tty: true
    networks: [ adosia-market-tx-builder ]

networks:
  adosia-market-tx-builder:
