version: "3.5"

services:

  # Transaction Builder Web Service
  adosia-market-tx-builder-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        LINUX_USERNAME: ${LINUX_USERNAME}
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}
        CARDANO_NODE_VERSION: ${CARDANO_NODE_VERSION}
        CARDANO_NODE_BUILD: ${CARDANO_NODE_BUILD}
        CARDANO_NETWORK: ${CARDANO_NETWORK}
    container_name: adosia-market-tx-builder-web
    user: "${CURRENT_UID}:${CURRENT_GID}"
    tty: true
    networks: [ adosia-market-tx-builder ]
    volumes:
      - ../application:/home/${LINUX_USERNAME}/application
      - cardano-node-db:/home/${LINUX_USERNAME}/cardano-node/db
    environment:
      - CARDANO_NODE_SOCKET_PATH=/home/${LINUX_USERNAME}/cardano-node/db/node.socket
    ports:
      - "8030:80"
      - "6000:6000"

volumes:
  cardano-node-db:

networks:
  adosia-market-tx-builder:
